apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-build-agent
  namespace: azure-build
spec:
  selector:
    matchLabels:
      app: azure-build-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: azure-build-agent
    spec:
      containers:
        - name: azure-build-agent
          image: >-
            image-registry.openshift-image-registry.svc:5000/azure-build/azure-build-agent:latest
          env:
            - name: AZP_URL
              valueFrom:
                secretKeyRef:
                  name: azdevops
                  key: AZP_URL
            - name: AZP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: azdevops
                  key: AZP_TOKEN
            - name: AZP_POOL
              valueFrom:
                secretKeyRef:
                  name: azdevops
                  key: AZP_POOL
            - name: AZP_PROXY_URL
              valueFrom:
                secretKeyRef:
                  name: azproxy
                  key: AZP_PROXY_URL
                optional: true
            - name: AZP_PROXY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: azproxy
                  key: AZP_PROXY_USERNAME
                optional: true
            - name: AZP_PROXY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: azproxy
                  key: AZP_PROXY_PASSWORD
                optional: true
          ports:
            - containerPort: 8080
          securityContext:
            privileged: true
      serviceAccount: azure-build-sa
      serviceAccountName: azure-build-sa
