kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: azure-build-agent
  namespace: azure-build
spec:
  successfulBuildsHistoryLimit: 1
  failedBuildsHistoryLimit: 3
  output:
    to:
      kind: ImageStreamTag
      name: azure-build-agent:latest
  source:
    dockerfile: |
      FROM registry.redhat.io/rhel8/dotnet-60-runtime:latest

      USER root
      COPY start.sh .
      RUN dnf install jq -y && \
          curl $AZP_AGENT_PACKAGE_LATEST_URL --output vsts-agent-linux-x64.tar.gz && \
          tar zxvf vsts-agent-linux-x64.tar.gz && \
          rm vsts-agent-linux-x64.tar.gz && \
          chmod 755 *.sh && chown -R default:root .
      USER 1001
      ENTRYPOINT ["./start.sh"]
    configMaps:
      - configMap:
          name: start-sh
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: dotnet-runtime:6.0
        namespace: openshift
      env:
        - name: AZP_AGENT_PACKAGE_LATEST_URL
          value: >-
            https://vstsagentpackage.azureedge.net/agent/2.206.1/vsts-agent-linux-x64-2.206.1.tar.gz
  runPolicy: Serial
