apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-build-agent
  namespace: azure-build
spec:
  selector:
    matchLabels:
      app: azure-build-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: azure-build-agent
    spec:
      containers:
        - name: azure-build-agent
          image: >-
            image-registry.openshift-image-registry.svc:5000/azure-build/azure-build-agent:latest
          envFrom:
          - secretRef:
              name: azdevops
          - secretRef:
              name: azproxy
              optional: true
          ports:
          - containerPort: 8080
          securityContext:
            runAsUser: 1001
      serviceAccount: azure-build-sa
      serviceAccountName: azure-build-sa
